## --------------------------------------------------------------------------------------------------------------------------
## Programming and idea by : Mohammad Hossein Salehinezhad
## GitLab : https://github.com/mrunix1998/docker-minio-cluster.git 
## Email : salehimohammad331@gmail.com
## Last update : Wed, 23 Feb 2022 17:09:25 +0330
## Minio v1.0.0 [Minio]
## --------------------------------------------------------------------------------------------------------------------------

version: '3.7'

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2022-02-18T01-50-10Z
  command: server --console-address ":9001" http://minio{1...4}/data{1...2}
  expose:
    - "9000"
    - "9001"
  environment:
    MINIO_ROOT_USER: minio
    MINIO_ROOT_PASSWORD: changeme
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

# starts 4 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  minio1:
    <<: *minio-common
    hostname: minio1
    container_name: minio1
    volumes:
      - /mnt/docker/apps/minio/data1-1:/data1
      - /mnt/docker/apps/minio/data1-2:/data2

  minio2:
    <<: *minio-common
    hostname: minio2
    container_name: minio2
    volumes:
      - /mnt/docker/apps/minio/data2-1:/data1
      - /mnt/docker/apps/minio/data2-2:/data2

  minio3:
    <<: *minio-common
    hostname: minio3
    container_name: minio3
    volumes:
      - /mnt/docker/apps/minio/data3-1:/data1
      - /mnt/docker/apps/minio/data3-2:/data2

  minio4:
    <<: *minio-common
    hostname: minio4
    container_name: minio4
    volumes:
      - /mnt/docker/apps/minio/data4-1:/data1
      - /mnt/docker/apps/minio/data4-2:/data2

  nginx:
    image: nginx:1.19.2-alpine
    container_name: nginx
    hostname: nginx
    volumes:
      - /mnt/docker/apps/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /mnt/docker/apps/nginx/certs/:/etc/nginx/certs/
    ports:
      - "80:80"
      - "443:443"
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
#volumes:
#  data1-1:
#  data1-2:
#  data2-1:
#  data2-2:
#  data3-1:
#  data3-2:
#  data4-1:
#  data4-2:
